# -*- coding: utf-8 -*-
"""POC_SHAMEER _INS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBZigqegQSYtkjbAdyu7l9ROiO-7Hmt1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
sam=files.upload()

sam=pd.read_csv("poc1insurance dataset.csv")
sam

sam.shape

sam.columns

sam.head(500)

sam.tail(100)

sam.info() #Technical information

sam.describe()

sam.isnull().sum()

sam.isnull().mean()

(sam==0).sum()

x=sam.iloc[:,[0,1,2,3,4,5]]   #x = sam.drop(['charges'],axis = 1)
y=sam.iloc[:,[6]]

x

y

# LabelEncoder
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()

x['sex']=la.fit_transform(x['sex'])
x

x['smoker']=la.fit_transform(x['smoker'])
x

x['region']=la.fit_transform(x['region'])
x

from sklearn.preprocessing import StandardScaler
scale_x=StandardScaler().fit_transform(x)

scale_x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,test_size=0.3,random_state=42)

x_train

x_test

y_train

y_test

from sklearn.linear_model import LinearRegression
war = LinearRegression()
war.fit(x_train,y_train)

y_predict = war.predict(x_test)
y_predict

plt.scatter(x_train.iloc[:,[2]],y_train,color = "green")
plt.plot(x_train,war.predict(x_train),color = "red")
plt.title("charges predection")
plt.xlabel("items")
plt.ylabel("charges")
plt.show()

from sklearn.metrics import r2_score
r2_score(y_predict,y_test)